name = "linters"
defaultTargets = ["Linters"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.18.0"

[[lean_lib]]
name = "Linters"
